default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 15432
  username: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: video_locadora_development

test:
  <<: *default
  database: video_locadora_test
  
production:
  url: <%= ENV['DATABASE_URL'] %>